//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSnooze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Azure_Snooze_Schedule
    {
        public string Server { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public int ID { get; set; }
        public string AppTeam { get; set; }
    }
}
