//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSnooze.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITSnoozeEntities : DbContext
    {
        public ITSnoozeEntities()
            : base("name=ITSnoozeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Azure_Snooze_Immediate> Azure_Snooze_Immediate { get; set; }
        public virtual DbSet<Azure_Snooze_Schedule> Azure_Snooze_Schedule { get; set; }
        public virtual DbSet<Azure_Snooze_Weekend> Azure_Snooze_Weekend { get; set; }
    }
}
